# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import market_seller_pb2 as market__seller__pb2


class MarketPlaceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterSeller = channel.unary_unary(
                '/market_communication_with_seller.MarketPlace/RegisterSeller',
                request_serializer=market__seller__pb2.RegisterSellerRequest.SerializeToString,
                response_deserializer=market__seller__pb2.StatusResponse.FromString,
                )
        self.SellItem = channel.unary_unary(
                '/market_communication_with_seller.MarketPlace/SellItem',
                request_serializer=market__seller__pb2.SellItemRequest.SerializeToString,
                response_deserializer=market__seller__pb2.StatusResponse.FromString,
                )
        self.UpdateItem = channel.unary_unary(
                '/market_communication_with_seller.MarketPlace/UpdateItem',
                request_serializer=market__seller__pb2.UpdateItemRequest.SerializeToString,
                response_deserializer=market__seller__pb2.StatusResponse.FromString,
                )
        self.DeleteItem = channel.unary_unary(
                '/market_communication_with_seller.MarketPlace/DeleteItem',
                request_serializer=market__seller__pb2.DeleteItemRequest.SerializeToString,
                response_deserializer=market__seller__pb2.StatusResponse.FromString,
                )
        self.DisplaySellerItems = channel.unary_stream(
                '/market_communication_with_seller.MarketPlace/DisplaySellerItems',
                request_serializer=market__seller__pb2.ProductDisplayRequest.SerializeToString,
                response_deserializer=market__seller__pb2.ProductDisplayResponse.FromString,
                )


class MarketPlaceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterSeller(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SellItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisplaySellerItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketPlaceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterSeller': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterSeller,
                    request_deserializer=market__seller__pb2.RegisterSellerRequest.FromString,
                    response_serializer=market__seller__pb2.StatusResponse.SerializeToString,
            ),
            'SellItem': grpc.unary_unary_rpc_method_handler(
                    servicer.SellItem,
                    request_deserializer=market__seller__pb2.SellItemRequest.FromString,
                    response_serializer=market__seller__pb2.StatusResponse.SerializeToString,
            ),
            'UpdateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateItem,
                    request_deserializer=market__seller__pb2.UpdateItemRequest.FromString,
                    response_serializer=market__seller__pb2.StatusResponse.SerializeToString,
            ),
            'DeleteItem': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteItem,
                    request_deserializer=market__seller__pb2.DeleteItemRequest.FromString,
                    response_serializer=market__seller__pb2.StatusResponse.SerializeToString,
            ),
            'DisplaySellerItems': grpc.unary_stream_rpc_method_handler(
                    servicer.DisplaySellerItems,
                    request_deserializer=market__seller__pb2.ProductDisplayRequest.FromString,
                    response_serializer=market__seller__pb2.ProductDisplayResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'market_communication_with_seller.MarketPlace', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MarketPlace(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterSeller(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/market_communication_with_seller.MarketPlace/RegisterSeller',
            market__seller__pb2.RegisterSellerRequest.SerializeToString,
            market__seller__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SellItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/market_communication_with_seller.MarketPlace/SellItem',
            market__seller__pb2.SellItemRequest.SerializeToString,
            market__seller__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/market_communication_with_seller.MarketPlace/UpdateItem',
            market__seller__pb2.UpdateItemRequest.SerializeToString,
            market__seller__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/market_communication_with_seller.MarketPlace/DeleteItem',
            market__seller__pb2.DeleteItemRequest.SerializeToString,
            market__seller__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DisplaySellerItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/market_communication_with_seller.MarketPlace/DisplaySellerItems',
            market__seller__pb2.ProductDisplayRequest.SerializeToString,
            market__seller__pb2.ProductDisplayResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
